Actually start staff badge range at 7 (#157)
* Actually start staff badge range at 7

Apparently, you can't override badge ranges in downstream config or you'll get an error like this:
```
sideboard.config.ConfigurationError: configuration validation error(s) (): [(['badge_ranges'], 'staff_badge', VdtValueTooLongError('the value "[\'25\', \'999\', \'7\', \'999\']" is too long.',))]
```

So this removes the 'override' and changes the original instead.